version: "2"

run:
  # Include test files or not.
  # Default: true
  tests: true

output:
  # Show statistics per linter.
  # Default: false
  show-stats: true

formatters:
  enable:
    - gofmt

linters:
  default: none
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true

    errcheck:
      # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
      # Such cases aren't reported by default.
      # Default: false
      check-blank: true
      # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
      # Such cases aren't reported by default.
      # Default: false
      check-type-assertions: true

    exhaustive:
      default-signifies-exhaustive: true

    gocritic:
      # Enable multiple checks by tags in addition to default checks.
      # Run `GL_DEBUG=gocritic golangci-lint run --enable=gocritic` to see all tags and checks.
      # See https://github.com/go-critic/go-critic#usage -> section "Tags".
      # Default: []
      enabled-tags: [diagnostic, style, performance, opinionated]

    gosec:
      excludes:
        - G505 # Blocklisted import (sha1 and etc.)
        - G401 # Use of weak cryptographic primitive

    sloglint:
      attr-only: true
      args-on-sep-lines: true

  enable:
    # Defaults
    - "errcheck"
    - "govet"
    - "ineffassign"
    - "staticcheck"
    - "unused"

    # Additional
    - "asasalint"
    - "bodyclose"
    - "contextcheck"
    - "durationcheck"
    - "errchkjson"
    - "errorlint"
    - "exhaustive"
    - "exptostd"
    - "forcetypeassert"
    - "gocheckcompilerdirectives"
    - "gocritic"
    - "goprintffuncname"
    - "gosec"
    - "gosmopolitan"
    - "iface"
    - "importas"
    - "inamedparam"
    - "loggercheck"
    - "makezero"
    - "mirror"
    - "musttag"
    - "nestif"
    - "nilerr"
    - "nilnesserr"
    - "nilnil"
    - "noctx"
    - "nolintlint"
    - "perfsprint"
    - "prealloc"
    - "predeclared"
    # - "protogetter"
    - "reassign"
    - "recvcheck"
    - "revive"
    - "rowserrcheck"
    - "sloglint"
    - "sqlclosecheck"
    - "staticcheck"
    - "testifylint"
    - "thelper"
    - "unconvert"
    - "usestdlibvars"
    - "usetesting"
    - "wastedassign"
    # - "wsl"

issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0

  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0
